### ISSUE TITLE
Update from 5.10 SDK

### ISSUE THREAD

**Issue by nedrichards** [flathub/xyz.z3ntu.razergenie#1]
I see the manifest uses the KDE 5.10 SDK which is based upon Qt 5.10. This is now out of security support and won't recieve further updates. It'd be good to move to either the 5.9 lts or the newer and fresher 5.11 SDK.

**Comment by z3ntu** [comment]
Is there somewhere where I can get a notification when a new runtime is out so I can update it?

**Comment by z3ntu** [comment]
Fixed in 8939c34e238f7310a92636b4310b236f29b3feff

**Comment by nedrichards** [comment]
Really good question! We talked about this topic in the Flatpak meeting at GUADEC last week, there aboslutely needs to be better communication to app developers about which runtimes are available, what their contents are and what their lifetimes and update schedules are.
