### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by makarov-roman** [flathub/xyz.z3ntu.razergenie#11]
Hi, not sure if it's a problem with packaging or the app itself. Fedora 40/Wayland. Let me know if any other context may be useful or if you will need to test it.

Thanks

Logs:
```bash
flatpak run xyz.z3ntu.razergenie
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb
```

**Comment by makarov-roman** [comment]
hm, I had `QT_QPA_PLATFORM=xcb`,
not sure if I set it long time ago to mitigate some issues with QT apps while I was running wayland, or it's set by OS itself.
Setting `QT_QPA_PLATFORM=wayland` helped. Closing the issue

**Comment by z3ntu** [comment]
I think this is due to `--socket=fallback-x11` in the flatpak, this doesn't allow any X11/X.org connections when you're on Wayland to narrow down the holes opened by flatpak.

**Comment by makarov-roman** [comment]
I had 
`QT_QPA_PLATFORM=xcb` in `/etc/environment`
