### ISSUE TITLE
Update to v0.8.1

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/xyz.z3ntu.razergenie#2]

**Comment by z3ntu** [comment]
Weird that I forgot... I'll update it in a couple of days!

**Comment by aldevel** [comment]
Lol, is it real? I assumed it's cuz there is no time or there are some difficulties although it's more then a year now since it was released. Anyways, nice work, keep it up.

**Comment by z3ntu** [comment]
Should be updated now.
