### ISSUE TITLE
Settings don't presist after reboot

### ISSUE THREAD

**Issue by peterlobster** [flathub/xyz.z3ntu.razergenie#7]
For some reason, I can't seem to get the settings to persist after a reboot. Seems to only happen with the FlatPak version.

**Comment by z3ntu** [comment]
Just to confirm, you're on v1.0.0 on the flatpak version?

**Comment by peterlobster** [comment]
> Just to confirm, you're on v1.0.0 on the flatpak version?

@z3ntu Thanks for the help. Yeah, it's v1.0.0.

**Comment by z3ntu** [comment]
There should really be no difference for this between flatpak version and non-flatpak version (if they're on the same software version) since all this communication happens through dbus. Can you double check on non-flatpak version please?

Also which devices do you have where this happens?

**Comment by peterlobster** [comment]
> There should really be no difference for this between flatpak version and non-flatpak version (if they're on the same software version) since all this communication happens through dbus. Can you double check on non-flatpak version please?

It seems like with the non-flatpak version, it works every time reliably. On the flatpak version, it only works sometimes. Maybe it works 1% of time.

FWIW I'm using dbus-broker, but I don't think it should matter.

> Also which devices do you have where this happens?

I have a lot of devices, but it happens on all of them. If you'd like, I can make a list if it's useful, but pretty much everything from keyboard, mouse, headphones, web cam, charging pad, etc...

**Comment by z3ntu** [comment]
Are you still seeing this issue? I've also just upgraded the Sdk, maybe that fixed something.

**Comment by z3ntu** [comment]
No response, closing.
