### ISSUE TITLE
Update Runtime again

### ISSUE THREAD

**Issue by rmburg** [flathub/xyz.z3ntu.razergenie#8]
CC @z3ntu 
`flatpak update` started logging these messages:

```
Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   xyz.z3ntu.razergenie

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   xyz.z3ntu.razergenie
```

**Comment by z3ntu** [comment]
And my yearly shout into the void that communication to app devs is non-existant (apart from issues like this): https://github.com/flathub/xyz.z3ntu.razergenie/issues/1#issuecomment-405717412

And which Sdk should be used now is also obscure as ever. https://docs.flatpak.org/en/latest/available-runtimes.html lists the runtimes but no versions. On the linked page at https://invent.kde.org/packaging/flatpak-kde-runtime there's zero info for people building on top of the runtime, which versions are supported, until when etc. At most I can see that the default branch is `qt5.15lts-22.08` (which will be `5.15-22.08` of the Sdk). But `qt5.15lts-23.08` branch also exists but is not default. Should it be used? Should it not? It's published on flathub so I'm assuming at least it's not experimental/beta/whatever anymore? But who knows.

**Comment by z3ntu** [comment]
Anyways #9 should fix it, once the test build is done would be nice if you could give it spin. FWIW a local build worked fine.

**Comment by rmburg** [comment]
Thanks you! I'm happy to test this when I'm back home tomorrow.

**Comment by rmburg** [comment]
When will the new version show up on Flathub?

**Comment by z3ntu** [comment]
Soon?

**Comment by rmburg** [comment]
Nice, the warning is gone :+1:
